<?php

use Illuminate\Database\Seeder;

class WheelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wheels')->delete();

        $wheels = array(
          array(
            'model' => 'ClubSport Wheel Base V2.5',
            'description' => 'The ClubSport Wheel Base V2.5 is a careful and precise evolution of the highly successful V2. It comes with​​ more advanced electronics and a new motor for improved feeling, functionality and even higher durability.',
            'diameter' => null,
            'rotation' => 900,
            'torque' => 8,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 3,
            'drive_id' => 2,
          ),
          array(
            'model' => 'CSL Elite PS4',
            'description' => 'The powerful brushless servo motor combined with the single belt drive deliver impressively detailed and strong force feedback, with ultra-smooth feeling and big ball bearings for lowest friction.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => 6,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 3,
            'drive_id' => 2,
          ),
          array(
            'model' => 'CSL Elite',
            'description' => 'The powerful brushless servo motor in combination with the single belt dr​ive, delivers incrediblly smooth and super-fast Force Feedback effects with instant acceleration, eliminating dead spots.',
            'diameter' => null,
            'rotation' => 1080,
            'torque' => 6,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 3,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T-GT',
            'description' => 'The T-GT offers accurate sensations to virtual racers to allow them to adapt their driving and enable them to improve their performance.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TS-XW Racer Sparco P310 Competition Mod',
            'description' => 'TS-XW Racer Sparco P310 Competition Mod is the first milestone of the collaboration between Thrustmaster and Sparco a highly realistic wheel, designed for competition.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TS-PC Racer',
            'description' => 'TS-PC Racer is Thrustmaster’s ultimate racing simulator for PC racers. It faithfully reproduces the car’s response and track conditions.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TS-PC Racer 488 Challenge Edition',
            'description' => 'For the 70th anniversary of the most famous racing brand worldwide, Ferrari, Thrustmaster is proud to present the TS-PC RACER Ferrari 488 Challenge Edition racing wheel.',
            'diameter' => 12.6,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T300RS',
            'description' => '1080 degree force feedback base featuring a brushless motor and detachable racing GT style wheel.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T300 RS GT',
            'description' => 'This special GT Edition of the T300 RS shows a new look of the detachable GT Style wheel and T3PA pedal set.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T300 Ferrari Integral Racing Wheel Alcantara Edition',
            'description' => 'This special edition of the T300RS includes an 8:10 scale replica of the wheel of the Ferrari 599XX EVO and a T3PA pedal set.',
            'diameter' => 11.8,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TX Racing Wheel Ferrari 458 Italia Edition',
            'description' => 'Developed in close collaboration with Microsoft, this 7:10 scale replica of the emblematic Ferrari 458 Italia wheel is fully dedicated to Xbox One, including Binder ID and Xbox One Guide button.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TX Racing Wheel Leather Edition',
            'description' => 'TX with upgraded leather wheel and T3PA three pedal set.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => null,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'G920',
            'description' => 'Steel ball bearings, stainless steel pedals and hand-stitched leather wheel grip.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => 2.2,
            'brushless_motor' => 0,
            'resolution' => 16,
            'brand_id' => 2,
            'drive_id' => 1,
          ),
          array(
            'model' => 'G29',
            'description' => 'Steel ball bearings, stainless steel pedals and hand-stitched leather wheel grip.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => 2.1,
            'brushless_motor' => 0,
            'resolution' => 16,
            'brand_id' => 2,
            'drive_id' => 1,
          ),
          array(
            'model' => 'T80',
            'description' => 'Bungee cord system offers linear resistance.',
            'diameter' => 12,
            'rotation' => 240,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => null,
            'brand_id' => 1,
            'drive_id' => 5,
          ),
          array(
            'model' => 'Ferrari 458 Spider',
            'description' => 'Like the T80 but styled like a Ferrari 458 Spider steering wheel.',
            'diameter' => 11,
            'rotation' => 240,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => null,
            'brand_id' => 1,
            'drive_id' => 5,
          ),
          array(
            'model' => 'Racing Wheel Overdrive',
            'description' => 'Full-size racing wheel and pedals',
            'diameter' => 11,
            'rotation' => 270,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => 16,
            'brand_id' => 4,
            'drive_id' => 5,
          ),
          array(
            'model' => 'Racing Wheel Apex',
            'description' => 'Full-size racing wheel and pedals',
            'diameter' => 11,
            'rotation' => 270,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => 16,
            'brand_id' => 4,
            'drive_id' => 5,
          ),
          array(
            'model' => 'AccuForce Pro V2 Complete',
            'description' => 'The SimXperience AccuForce Pro V2 "Complete" is a professional racing simulation steering system. When combined with todays best racing simulation games, the AccuForce Pro is as close as you can get to driving the real thing and is delivered in a convenient, ready to run, plug-n-play package.',
            'diameter' => 12.5,
            'rotation' => 4500,
            'torque' => 13,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 5,
            'drive_id' => 4,
          ),
          array(
            'model' => 'SimSteering2 FFB System',
            'description' => 'A high performance simulator steering system for professional use. Provides top quality force feedback and control over simulation.',
            'diameter' => null,
            'rotation' => 1500,
            'torque' => 26,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 6,
            'drive_id' => 4,
          ),
          array(
            'model' => 'SimuCUBE based OSW kit Biss-C',
            'description' => 'SimuCUBE offers the straightest road to a successful professional grade OpenSimWheel system.',
            'diameter' => null,
            'rotation' => null,
            'torque' => 30,
            'brushless_motor' => 1,
            'resolution' => null,
            'brand_id' => 15,
            'drive_id' => 4,
          ),
          array(
            'model' => 'SW12C',
            'description' => 'Direct Drive Wheel built around the MiGE 90ST-M04025 with a 5,000 ppr /20,000 cpr incremental encoder.',
            'diameter' => null,
            'rotation' => null,
            'torque' => 12,
            'brushless_motor' => 1,
            'resolution' => null,
            'brand_id' => 16,
            'drive_id' => 4,
          ),
          array(
            'model' => 'Mini-Mite Direct Drive Servo Base',
            'description' => 'Direct drive system eliminates friction and reduces rotating mass. User selectable modes allow easy selection of linear performance, peak performance, soft performance, child mode.',
            'diameter' => null,
            'rotation' => 6000,
            'torque' => 13,
            'brushless_motor' => 1,
            'resolution' => null,
            'brand_id' => 7,
            'drive_id' => 4,
          ),
          array(
            'model' => 'TMX Force Feedback',
            'description' => 'Force Feedback system: Mixed belt-pulley and gears system with metal ball-bearing axle.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => 12,
            'brand_id' => 1,
            'drive_id' => 3,
          ),
          array(
            'model' => 'TMX PRO',
            'description' => 'A TMX system with upgraded T3PA pedals.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => 12,
            'brand_id' => 1,
            'drive_id' => 3,
          ),
          array(
            'model' => 'T150 Force Feedback',
            'description' => 'Price-to-performance ratio and multi-platform versatility.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => 12,
            'brand_id' => 1,
            'drive_id' => 3,
          ),
          array(
            'model' => 'T150 PRO',
            'description' => 'A T150 system with T3PA pedals.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => null,
            'brushless_motor' => 0,
            'resolution' => 12,
            'brand_id' => 1,
            'drive_id' => 3,
          ),
        );

        foreach($wheels as &$wheel) {
          $wheel['created_at'] = Carbon\Carbon::now();
          $wheel['updated_at'] = Carbon\Carbon::now();
        }
        DB::table('wheels')->insert($wheels);
    }
}
